#!/bin/sh
#
# smudge the files 
#
utildir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
source $utildir/common.sh

if_large=false
filepath="$@"
LargeOrNot $filepath #check if it is a large binary file
if $if_large; then
  echo "!!! $filepath is a large binary file and should be trackted through a link !!!" >&2
else
  while read myline; do
    echo "$myline"
  done  < /dev/stdin
fi
